name: SauceDemo UI Test Automation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: maven
    
    - name: Install Playwright Browsers
      run: mvn playwright install
    
    - name: Build with Maven
      run: mvn clean verify
      env:
        # Add any environment variables needed for tests
        TEST_ENV: ci
    
    - name: Generate Test Report
      run: mvn surefire-report:report
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          target/surefire-reports/
          target/site/
        retention-days: 30
    
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      if: always()
      with:
        report_paths: '**/surefire-reports/*.xml'
        check_name: 'Test Results'
        fail_on_failure: true
    
    - name: Notify on Failure
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Test Failure in CI Pipeline',
            body: 'Tests failed in the CI pipeline. Please check the [workflow run](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}) for details.'
          }) 